- name: Download Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: "0644"

- name: Dearmor Microsoft GPG key
  ansible.builtin.shell: |
    gpg --dearmor < /tmp/microsoft.asc > /etc/apt/keyrings/packages.microsoft.gpg
  args:
    creates: /etc/apt/keyrings/packages.microsoft.gpg
  become: true

- name: Add VSCode apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
  become: true

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
  become: true

- name: Download Brave GPG key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Add Brave apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave-browser-release
  become: true

- name: Install Brave
  ansible.builtin.apt:
    name: brave-browser
    state: present
    update_cache: true
  become: true
